<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSGdElePrtService" xmlns:gdeupsb="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSGdElePrtService/Schema" name="GDEUPSGdElePrtService" targetNamespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSGdElePrtService">
  <wsdl:types>
    <xsd:schema targetNamespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSGdElePrtService">
      <xsd:import namespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSGdElePrtService/Schema" schemaLocation="GDEUPSGdElePrtService.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="eleClrInfQryPrtRequestMessage">
    <wsdl:part name="eleClrInfQryPrtRequest" element="gdeupsb:eleClrInfQryPrt"/>
  </wsdl:message>
  <wsdl:message name="eleClrInfQryPrtResponseMessage">
    <wsdl:part name="eleClrInfQryPrtResponse" element="gdeupsb:eleClrInfQryPrtResponse"/>
  </wsdl:message>
  <wsdl:portType name="GDEUPSGdElePrtServicePortType">
    <wsdl:operation name="eleClrInfQryPrt">
      <wsdl:documentation/>
      <wsdl:input message="tns:eleClrInfQryPrtRequestMessage"/>
      <wsdl:output message="tns:eleClrInfQryPrtResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GDEUPSGdElePrtServiceSoapBinding" type="tns:GDEUPSGdElePrtServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="eleClrInfQryPrt">
      <soap:operation soapAction="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSGdElePrtService/eleClrInfQryPrt"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GDEUPSGdElePrtService">
    <wsdl:port name="GDEUPSGdElePrtServicePort" binding="tns:GDEUPSGdElePrtServiceSoapBinding">
      <soap:address location="http://127.0.0.1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
