<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSTrspService" xmlns:gdeupsb="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSTrspService/Schema" name="GDEUPSTrspService" targetNamespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSTrspService">
  <wsdl:types>
    <xsd:schema targetNamespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSTrspService">
      <xsd:import namespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSTrspService/Schema" schemaLocation="GDEUPSTrspService.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="checkTrspFileRequestMessage">
    <wsdl:part name="checkTrspFileRequest" element="gdeupsb:checkTrspFile"/>
  </wsdl:message>
  <wsdl:message name="checkTrspFileResponseMessage">
    <wsdl:part name="checkTrspFileResponse" element="gdeupsb:checkTrspFileResponse"/>
  </wsdl:message>
  <wsdl:portType name="GDEUPSTrspServicePortType">
    <wsdl:operation name="checkTrspFile">
      <wsdl:documentation/>
      <wsdl:input message="tns:checkTrspFileRequestMessage"/>
      <wsdl:output message="tns:checkTrspFileResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GDEUPSTrspServiceSoapBinding" type="tns:GDEUPSTrspServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="checkTrspFile">
      <soap:operation soapAction="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.GDEUPSTrspService/checkTrspFile"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GDEUPSTrspService">
    <wsdl:port name="GDEUPSTrspServicePort" binding="tns:GDEUPSTrspServiceSoapBinding">
      <soap:address location="http://127.0.0.1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
