<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.HSSCChargeTestService" xmlns:gdeupsb="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.HSSCChargeTestService/Schema" name="HSSCChargeTestService" targetNamespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.HSSCChargeTestService">
  <wsdl:types>
    <xsd:schema targetNamespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.HSSCChargeTestService">
      <xsd:import namespace="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.HSSCChargeTestService/Schema" schemaLocation="HSSCChargeTestService.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="hsscFeeQueryRequestMessage">
    <wsdl:part name="hsscFeeQueryRequest" element="gdeupsb:hsscFeeQuery"/>
  </wsdl:message>
  <wsdl:message name="hsscFeeQueryResponseMessage">
    <wsdl:part name="hsscFeeQueryResponse" element="gdeupsb:hsscFeeQueryResponse"/>
  </wsdl:message>
  <wsdl:portType name="HSSCChargeTestServicePortType">
    <wsdl:operation name="hsscFeeQuery">
      <wsdl:documentation/>
      <wsdl:input message="tns:hsscFeeQueryRequestMessage"/>
      <wsdl:output message="tns:hsscFeeQueryResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HSSCChargeTestServiceSoapBinding" type="tns:HSSCChargeTestServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hsscFeeQuery">
      <soap:operation soapAction="http://gdeupsb.service.bankcomm.com/basic/atomic/operation.HSSCChargeTestService/hsscFeeQuery"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HSSCChargeTestService">
    <wsdl:port name="HSSCChargeTestServicePort" binding="tns:HSSCChargeTestServiceSoapBinding">
      <soap:address location="http://127.0.0.1"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
